checkoutLocation: '.'

ports:
  - port: 2181 # zookeeper
    onOpen: notify
  - port: 9092 # kafka
    onOpen: notify
  - port: 9101 # kafka jmx
    onOpen: notify
image:
  file: .gitpod.Dockerfile
tasks:
  - name: setup
    init: |
      mkdir kafka_cli
      wget https://downloads.apache.org/kafka/3.1.2/kafka_2.13-3.1.2.tgz -P kafka_cli
      tar -xzf kafka_cli/kafka_2.13-3.1.2.tgz --directory kafka_cli
      echo 'export PATH="/workspace/kafka_cli/kafka_2.13-3.1.2/bin:$PATH"' >> ~/.bashrc
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
jetbrains:
  intellij:
    prebuilds:
      version: stable